export const Currencies = [
    {
        short: 'USD',
        full_name: 'United States Dollar',
        locale: 'en_US',
        symbol: '$',
    },
    {
        short: 'AED',
        full_name: 'United Arab Emirates Dirham',
        locale: 'ar_AE',
        symbol: 'د.إ.',
    },
    {
        short: 'ARS',
        full_name: 'Argentine Peso',
        locale: 'es_AR',
        symbol: '$',
    },
    {
        short: 'AUD',
        full_name: 'Australian Dollar',
        locale: 'en_AU',
        symbol: '$',
    },
    {
        short: 'BDT',
        full_name: 'Bangladeshi Taka',
        locale: 'bn_BD',
        symbol: '৳',
    },
    {
        short: 'BHD',
        full_name: 'Bahraini Dinar',
        locale: 'ar_BH',
        symbol: 'د.ب.',
    },
    {
        short: 'BRL',
        full_name: 'Brazilian Real',
        locale: 'pt_BR',
        symbol: 'R$',
    },
    {
        short: 'CAD',
        full_name: 'Canadian Dollar',
        locale: 'en_CA',
        symbol: '$',
    },
    {
        short: 'CHF',
        full_name: 'Swiss Franc',
        locale: 'de_CH',
        symbol: 'CHF',
    },
    {
        short: 'CLP',
        full_name: 'Chilean Peso',
        locale: 'es_CL',
        symbol: '$',
    },
    {
        short: 'CZK',
        full_name: 'Czech Koruna',
        locale: 'cs',
        symbol: 'Kč',
    },
    {
        short: 'CNY',
        full_name: 'Chinese Yuan',
        locale: 'zh_CN',
        symbol: '￥',
    },
    {
        short: 'DKK',
        full_name: 'Danish Krone',
        locale: 'da_DK',
        symbol: 'kr',
    },
    {
        short: 'EUR',
        full_name: 'Euro',
        locale: 'de',
        symbol: '€',
    },
    {
        short: 'GBP',
        full_name: 'British Pound Sterling',
        locale: 'en_GB',
        symbol: '£',
    },
    {
        short: 'HKD',
        full_name: 'Hong Kong Dollar',
        locale: 'zh_HK',
        symbol: 'HK$',
    },
    {
        short: 'HUF',
        full_name: 'Hungarian Forint',
        locale: 'hu_HU',
        symbol: 'Ft',
    },
    {
        short: 'IDR',
        full_name: 'Indonesian Rupiah',
        locale: 'id',
        symbol: 'Rp',
    },
    {
        short: 'ILS',
        full_name: 'Israeli Sheqel',
        locale: 'he',
        symbol: '₪',
    },
    {
        short: 'INR',
        full_name: 'Indian Rupee',
        locale: 'en_IN',
        symbol: '₹',
    },
    {
        short: 'JPY',
        full_name: 'Japanese Yen',
        locale: 'ja',
        symbol: '¥',
    },
    {
        short: 'KRW',
        full_name: 'South Korean Won',
        locale: 'ko_KR',
        symbol: '₩',
    },
    {
        short: 'KWD',
        full_name: 'Kuwaiti Dinar',
        locale: 'ar_KW',
        symbol: 'د.ك.',
    },
    {
        short: 'LKR',
        full_name: 'Sri Lankan Rupee',
        locale: 'si',
        symbol: 'Rs',
    },
    {
        short: 'MMK',
        full_name: 'Burmese Kyat',
        locale: 'my',
        symbol: 'K',
    },
    {
        short: 'MXN',
        full_name: 'Mexican Peso',
        locale: 'en_MX',
        symbol: '$',
    },
    {
        short: 'MYR',
        full_name: 'Malaysian Ringgit',
        locale: 'ms_MY',
        symbol: 'MR',
    },
    {
        short: 'NGN',
        full_name: 'Nigerian Naira',
        locale: 'en_NG',
        symbol: '₦',
    },
    {
        short: 'NOK',
        full_name: 'Norwegian Krone',
        locale: 'nb_NO',
        symbol: 'kr',
    },
    {
        short: 'NZD',
        full_name: 'New Zealand Dollar',
        locale: 'en_NZ',
        symbol: '$',
    },
    {
        short: 'PHP',
        full_name: 'Philippine Peso',
        locale: 'fil',
        symbol: '₱',
    },
    {
        short: 'PKR',
        full_name: 'Pakistani Rupee',
        locale: 'ur_PK',
        symbol: 'ر',
    },
    {
        short: 'PLN',
        full_name: 'Polish Zloty',
        locale: 'pl',
        symbol: 'zł',
    },
    {
        short: 'RUB',
        full_name: 'Russian Ruble',
        locale: 'ru',
        symbol: '₽',
    },
    {
        short: 'SAR',
        full_name: 'Saudi Riyal',
        locale: 'ar_SA',
        symbol: 'ر.س.',
    },
    {
        short: 'SEK',
        full_name: 'Swedish Krona',
        locale: 'sv_SE',
        symbol: 'Kr',
    },
    {
        short: 'SGD',
        full_name: 'Singapore Dollar',
        locale: 'en_SG',
        symbol: '$',
    },
    {
        short: 'THB',
        full_name: 'Thai Baht',
        locale: 'th',
        symbol: '฿',
    },
    {
        short: 'TRY',
        full_name: 'Turkish Lira',
        locale: 'tr_TR',
        symbol: '₺',
    },
    {
        short: 'TWD',
        full_name: 'New Taiwan Dollar',
        locale: 'zh_TW',
        symbol: '$',
    },
    {
        short: 'UAH',
        full_name: 'Ukrainian Hryvnia',
        locale: 'uk',
        symbol: '₴',
    },
    {
        short: 'VEF',
        full_name: 'Venezuelan Bolívar',
        locale: 'es_VE',
        symbol: 'Bs',
    },
    {
        short: 'VND',
        full_name: 'Vietnamese Dong',
        locale: 'vi',
        symbol: '₫',
    },
    {
        short: 'ZAR',
        full_name: 'South African Rand',
        locale: 'en_ZA',
        symbol: 'R',
    },
];
