// Include currency meta and rate
// - Seed BTC/{Currency} rate
export default [
    {
        short: 'USD',
        full_name: 'United States Dollar',
        locale: 'en_US',
        symbol: '$',
        rate: 69000,
    },
    {
        short: 'AED',
        full_name: 'United Arab Emirates Dirham',
        locale: 'ar_AE',
        symbol: 'د.إ.',
        rate: 250583,
    },
    {
        short: 'ARS',
        full_name: 'Argentine Peso',
        locale: 'es_AR',
        symbol: '$',
        rate: 61007305,
    },
    {
        short: 'AUD',
        full_name: 'Australian Dollar',
        locale: 'en_AU',
        symbol: '$',
        rate: 102873,
    },
    {
        short: 'BDT',
        full_name: 'Bangladeshi Taka',
        locale: 'bn_BD',
        symbol: '৳',
        rate: 8000028,
    },
    {
        short: 'BHD',
        full_name: 'Bahraini Dinar',
        locale: 'ar_BH',
        symbol: 'د.ب.',
        rate: 25722,
    },
    {
        short: 'BRL',
        full_name: 'Brazilian Real',
        locale: 'pt_BR',
        symbol: 'R$',
        rate: 355079,
    },
    {
        short: 'CAD',
        full_name: 'Canadian Dollar',
        locale: 'en_CA',
        symbol: '$',
        rate: 93268,
    },
    {
        short: 'CHF',
        full_name: 'Swiss Franc',
        locale: 'de_CH',
        symbol: 'CHF',
        rate: 61736,
    },
    {
        short: 'CLP',
        full_name: 'Chilean Peso',
        locale: 'es_CL',
        symbol: '$',
        rate: 62600521,
    },
    {
        short: 'CZK',
        full_name: 'Czech Koruna',
        locale: 'cs',
        symbol: 'Kč',
        rate: 1561413,
    },
    {
        short: 'CNY',
        full_name: 'Chinese Yuan',
        locale: 'zh_CN',
        symbol: '￥',
        rate: 484418,
    },
    {
        short: 'DKK',
        full_name: 'Danish Krone',
        locale: 'da_DK',
        symbol: 'kr',
        rate: 470265,
    },
    {
        short: 'EUR',
        full_name: 'Euro',
        locale: 'de',
        symbol: '€',
        rate: 63046,
    },
    {
        short: 'GBP',
        full_name: 'British Pound Sterling',
        locale: 'en_GB',
        symbol: '£',
        rate: 53673,
    },
    {
        short: 'HKD',
        full_name: 'Hong Kong Dollar',
        locale: 'zh_HK',
        symbol: 'HK$',
        rate: 533182,
    },
    {
        short: 'HUF',
        full_name: 'Hungarian Forint',
        locale: 'hu_HU',
        symbol: 'Ft',
        rate: 24554785,
    },
    {
        short: 'IDR',
        full_name: 'Indonesian Rupiah',
        locale: 'id',
        symbol: 'Rp',
        rate: 1109341957,
    },
    {
        short: 'ILS',
        full_name: 'Israeli Sheqel',
        locale: 'he',
        symbol: '₪',
        rate: 253505,
    },
    {
        short: 'INR',
        full_name: 'Indian Rupee',
        locale: 'en_IN',
        symbol: '₹',
        rate: 5686234,
    },
    {
        short: 'JPY',
        full_name: 'Japanese Yen',
        locale: 'ja',
        symbol: '¥',
        rate: 10719623,
    },
    {
        short: 'KRW',
        full_name: 'South Korean Won',
        locale: 'ko_KR',
        symbol: '₩',
        rate: 94405081,
    },
    {
        short: 'KWD',
        full_name: 'Kuwaiti Dinar',
        locale: 'ar_KW',
        symbol: 'د.ك.',
        rate: 20937,
    },
    {
        short: 'LKR',
        full_name: 'Sri Lankan Rupee',
        locale: 'si',
        symbol: 'Rs',
        rate: 20558038,
    },
    {
        short: 'MMK',
        full_name: 'Burmese Kyat',
        locale: 'my',
        symbol: 'K',
        rate: 143025958,
    },
    {
        short: 'MXN',
        full_name: 'Mexican Peso',
        locale: 'en_MX',
        symbol: '$',
        rate: 1161557,
    },
    {
        short: 'MYR',
        full_name: 'Malaysian Ringgit',
        locale: 'ms_MY',
        symbol: 'MR',
        rate: 321011,
    },
    {
        short: 'NGN',
        full_name: 'Nigerian Naira',
        locale: 'en_NG',
        symbol: '₦',
        rate: 102163618,
    },
    {
        short: 'NOK',
        full_name: 'Norwegian Krone',
        locale: 'nb_NO',
        symbol: 'kr',
        rate: 719254,
    },
    {
        short: 'NZD',
        full_name: 'New Zealand Dollar',
        locale: 'en_NZ',
        symbol: '$',
        rate: 111419,
    },
    {
        short: 'PHP',
        full_name: 'Philippine Peso',
        locale: 'fil',
        symbol: '₱',
        rate: 3996300,
    },
    {
        short: 'PKR',
        full_name: 'Pakistani Rupee',
        locale: 'ur_PK',
        symbol: 'ر',
        rate: 18960903,
    },
    {
        short: 'PLN',
        full_name: 'Polish Zloty',
        locale: 'pl',
        symbol: 'zł',
        rate: 269662,
    },
    {
        short: 'RUB',
        full_name: 'Russian Ruble',
        locale: 'ru',
        symbol: '₽',
        rate: 6166237,
    },
    {
        short: 'SAR',
        full_name: 'Saudi Riyal',
        locale: 'ar_SA',
        symbol: 'ر.س.',
        rate: 255795,
    },
    {
        short: 'SEK',
        full_name: 'Swedish Krona',
        locale: 'sv_SE',
        symbol: 'Kr',
        rate: 721620,
    },
    {
        short: 'SGD',
        full_name: 'Singapore Dollar',
        locale: 'en_SG',
        symbol: '$',
        rate: 92241,
    },
    {
        short: 'THB',
        full_name: 'Thai Baht',
        locale: 'th',
        symbol: '฿',
        rate: 2509401,
    },
    {
        short: 'TRY',
        full_name: 'Turkish Lira',
        locale: 'tr_TR',
        symbol: '₺',
        rate: 2201000,
    },
    {
        short: 'TWD',
        full_name: 'New Taiwan Dollar',
        locale: 'zh_TW',
        symbol: '$',
        rate: 2215451,
    },
    {
        short: 'UAH',
        full_name: 'Ukrainian Hryvnia',
        locale: 'uk',
        symbol: '₴',
        rate: 2759096,
    },
    {
        short: 'VEF',
        full_name: 'Venezuelan Bolívar',
        locale: 'es_VE',
        symbol: 'Bs',
        rate: 6828.72,
    },
    {
        short: 'VND',
        full_name: 'Vietnamese Dong',
        locale: 'vi',
        symbol: '₫',
        rate: 1735774586,
    },
    {
        short: 'ZAR',
        full_name: 'South African Rand',
        locale: 'en_ZA',
        symbol: 'R',
        rate: 1285426,
    },
];
