import {
    BREEZ_INVITE_CODE,
    BREEZ_SDK_SPARK_API,
    GL_CUSTOM_NOBODY_CERT,
    GL_CUSTOM_NOBODY_KEY,
} from '@env';

// Path: modules/env.ts
export const _BREEZ_INVITE_CODE_ = BREEZ_INVITE_CODE;
export const _BREEZ_SDK_SPARK_API_ = BREEZ_SDK_SPARK_API;
export const _GL_CUSTOM_NOBODY_CERT_ = GL_CUSTOM_NOBODY_CERT;
export const _GL_CUSTOM_NOBODY_KEY_ = GL_CUSTOM_NOBODY_KEY;
